### ISSUE TITLE
感谢大佬，已经成功了，问一下有无封号风险

### ISSUE THREAD

**Issue by AR307** [tanenrumu/ArkNightsForMinor#11]
感谢大佬，已经成功了，问一下有无封号风险

**Comment by leisiyu1** [comment]
肯定是有的（
管他呢，封号和未成年有多大区别（）
还可以再薅个月卡

**Comment by AR307** [comment]
> 肯定是有的（ 他呢，封号和还能有多大区别（） 还可以薅月卡

？薅个月卡是（）

**Comment by leisiyu1** [comment]
之前不是月卡补偿了吗？
再登录再薅一遍（
